[package]
name = "fawi-search"
version.workspace = true
edition.workspace = true

[dependencies]
fawi-core = { path = "../fawi-core" }
fawi-storage = { path = "../fawi-storage" }
anyhow.workspace = true
async-trait.workspace = true
tokio.workspace = true
tracing.workspace = true
fastembed = { version = "6", default-features = false, features = [
    "ort-download-binaries-native-tls",
    "hf-hub-native-tls",
] }