[package]
name = "okf-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "okf"
path = "src/main.rs"

[dependencies]
okf-server = { path = "../okf-server" }
okf-gui = { path = "../okf-gui", features = ["ssr"] }
okf-search = { path = "../okf-search" }
okf-storage = { path = "../okf-storage" }
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
